<?php namespace App\Database\Migrations;

class CreateGuestsPermissions extends \CodeIgniter\Database\Migration {

        private $table = 'permissions';
        public function up()
        {
                  $data = [
                      [
                          'function_name' => 'show guest details',
                          'function_description' => 'show guest details',
                          'slugs' => 'show-guest',
                          'name_on_class' => 'show_guest',
                          'page_title' => 'guest details',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '1',
                          'table_name' => 'guests',
                          'func_action' => 'show',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'create guest',
                          'function_description' => 'create guest',
                          'slugs' => 'add-guest',
                          'name_on_class' => 'add_guest',
                          'page_title' => 'create a guest',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '2',
                          'table_name' => 'guests',
                          'func_action' => 'add',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'list of guest',
                          'function_description' => 'guest',
                          'slugs' => 'list-guest',
                          'name_on_class' => 'index',
                          'page_title' => 'list of guest',
                          'module_id' => '3',
                          'link_icon' => '<i class="fas fa-users"></i>',
                          'order' => '3',
                          'table_name' => 'guests',
                          'func_action' => 'link',
                          'func_type' => 1,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'edit guest',
                          'function_description' => 'edit guest',
                          'slugs' => 'edit-guest',
                          'name_on_class' => 'edit_guest',
                          'page_title' => 'edit guest',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '4',
                          'table_name' => 'guests',
                          'func_action' => 'edit',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'delete guest',
                          'function_description' => 'delete guest',
                          'slugs' => 'delete-guest',
                          'name_on_class' => 'delete_guest',
                          'page_title' => 'delete guest',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '5',
                          'table_name' => 'guests',
                          'func_action' => 'delete',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'create visit',
                          'function_description' => 'create visit',
                          'slugs' => 'add-visit',
                          'name_on_class' => 'add',
                          'page_title' => 'create a visit',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '6',
                          'table_name' => 'visits',
                          'func_action' => 'add',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'list of visits',
                          'function_description' => 'guests',
                          'slugs' => 'list-visit',
                          'name_on_class' => 'index',
                          'page_title' => 'list of patients relatives',
                          'module_id' => '3',
                          'link_icon' => '<i class="fas fa-users"></i>',
                          'order' => '7',
                          'table_name' => 'visits',
                          'func_action' => 'link',
                          'func_type' => 2,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'edit visit',
                          'function_description' => 'edit visit',
                          'slugs' => 'edit-visit',
                          'name_on_class' => 'edit',
                          'page_title' => 'edit visit',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '8',
                          'table_name' => 'visits',
                          'func_action' => 'edit',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'delete visit',
                          'function_description' => 'delete visit',
                          'slugs' => 'delete-visit',
                          'name_on_class' => 'delete',
                          'page_title' => 'delete visit',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '9',
                          'table_name' => 'visits',
                          'func_action' => 'delete',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                        'function_name' => 'list of dashboard',
                        'function_description' => 'dashboard',
                        'slugs' => 'list-dashboard',
                        'name_on_class' => 'dashboard',
                        'page_title' => 'list of dashboard',
                        'module_id' => '2',
                        'link_icon' => '<i class="fas fa-users"></i>',
                        'order' => '10',
                        'table_name' => 'guests',
                        'func_action' => 'link',
                        'func_type' => 1,
                        'allowed_roles' => "[1]",
                        'status' => 'a',
                        'created_at' => date('Y-m-d H:i:s')
                      ],
                      // [
                      //     'function_name' => 'print checklist',
                      //     'function_description' => 'print checklist',
                      //     'slugs' => 'print-checklist',
                      //     'name_on_class' => 'print',
                      //     'page_title' => 'print checklist',
                      //     'module_id' => '3',
                      //     'link_icon' => '',
                      //     'order' => '11',
                      //     'table_name' => 'guests',
                      //     'func_action' => 'print',
                      //     'func_type' => 3,
                      //     'allowed_roles' => "[1]",
                      //     'status' => 'a',
                      //     'created_at' => date('Y-m-d H:i:s')
                      // ],
                      [
                          'function_name' => 'student list',
                          'function_description' => 'student list',
                          'slugs' => 'student-list',
                          'name_on_class' => 'student_list',
                          'page_title' => 'student list',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '11',
                          'table_name' => 'guests',
                          'func_action' => 'link',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'print total studens',
                          'function_description' => 'print total students',
                          'slugs' => 'print-total-students',
                          'name_on_class' => 'print_total_students',
                          'page_title' => 'print total students',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '12',
                          'table_name' => 'guests',
                          'func_action' => 'print',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'print guest',
                          'function_description' => 'print guest',
                          'slugs' => 'print-guest',
                          'name_on_class' => 'print_guest',
                          'page_title' => 'print guest',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '13',
                          'table_name' => 'guests',
                          'func_action' => 'print_g',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                      [
                          'function_name' => 'print summary',
                          'function_description' => 'print summary',
                          'slugs' => 'print-summary',
                          'name_on_class' => 'print_summary',
                          'page_title' => 'print summary',
                          'module_id' => '3',
                          'link_icon' => '',
                          'order' => '14',
                          'table_name' => 'guests',
                          'func_action' => 'print_summary',
                          'func_type' => 3,
                          'allowed_roles' => "[1]",
                          'status' => 'a',
                          'created_at' => date('Y-m-d H:i:s')
                      ],
                ];
                $db      = \Config\Database::connect();
                $builder = $db->table($this->table);
                $builder->insertBatch($data);
        }

        public function down()
        {
                // $this->forge->dropTable($this->table);
        }
}
